apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reader
rules:
  - apiGroups: ["*"]
    resources: ["deployments", "configmaps", "pods", "services","secrets", "namespaces"]
    verbs: ["get", "list", "watch","create"]
  
